CREATE TABLE Client (
	Id INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	ClientName NVARCHAR(255) NOT NULL UNIQUE,
	IsActivated BIT NOT NULL
);
GO

CREATE TABLE WorkType (
	Id INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	Name NVARCHAR(255) NOT NULL UNIQUE,
	Rate DECIMAL(18, 2) NOT NULL
);
GO

CREATE TABLE WorkDone (
    Id INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
    ClientId INT NOT NULL REFERENCES Client (Id),
    WorkTypeId INT NOT NULL REFERENCES WorkType (Id),
    StartedOn DATETIMEOFFSET NOT NULL,
    EndedOn DATETIMEOFFSET NULL
)
GO